Add some Markdown flourishes and some grammar tweaks
larryhastings/appeal pull request #2
Opened 2021-12-22 00:09 UTC by brettcannon

2021-12-22 01:09 UTC, larryhastings commented on README.md
> +`docopt`, and `Typer`.  But Appeal takes a refreshing new
Typer!  That's the one I couldn't remember.  Thanks!

2021-12-22 01:13 UTC, larryhastings requested changes

2021-12-22 01:13 UTC, larryhastings commented on README.md
> +work with Appeal by defining functions, shouldn't you
"you shouldn't", not "shouldn't you"

2021-12-22 19:04 UTC, brettcannon commented on README.md
> +work with Appeal by defining functions, shouldn't you
```suggestion
work with Appeal by defining functions, you shouldn't
```

2021-12-23 01:31 UTC, merged

2021-12-23 01:33 UTC, larryhastings commented
Thanks, Brett!  I'm so pleased to get your contribution.  Merry Christmas!